config/routes.rb
MusicApp::Application.routes.draw do
  resources :bands
  resources :albums
  resources :tracks
  resources :notes
  resources :users
  resource  :session

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :recording, :band_id
  validates :recording, :inclusion => ['live', 'studio'] # should work.

  belongs_to :band
  has_many :tracks, :dependent => :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :track_id

  belongs_to :track
  #belongs_to :user



end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title, :album_id, :track_type, :lyrics

  belongs_to :album
  has_many :notes
end

app/models/user.rb
# require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    #self.password_digest == BCrypt::Password(password)
    BCrypt::Password.new(self.password_digest) == password

  end

  def reset_session_token!
    self.session_token = SecureRandom::base64(32)
    self.save!

    self.session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def show

    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    render :show
  end

  def new
    @bands = Band.all
    @album = Album.new #necessary for refilling forms?
    render :new
  end

  def create
    @bands = Band.all
    @album = Album.new(params[:album])
    if @album.save
      redirect_to Band.find(@album.band_id)
    else
      render :new
    end

  end

  def edit
    @album = Album.find(params[:album][:id])

    render :edit
  end

  def update
    @album = Album.find(params[:album][:id])
    @album.update_attributes(params[:album])
    if @album.save
      redirect_to @album
    else
      render :edit
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy

    redirect_to albums_url
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    session_token = session[:session_token]
    return nil if session_token.nil?

    User.find_by_session_token(session_token)
    return
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new #necessary for refilling forms?
    render :new
  end

  def create
    @band = Band.new(params[:band])
    if @band.save
      redirect_to bands_url
    else
      render :new
    end

  end

  def edit
    @band = Band.find(params[:band][:id])

    render :edit
  end

  def update
    @band = Band.find(params[:band][:id])
    @band.update_attributes(params[:band])
    if @band.save
      redirect_to @band
    else
      render :edit
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy

    redirect_to bands_url
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
    render :index
  end

  def show
    @note = Note.find(params[:id])
    @track = Track.find(@note.track_id)
    render :show
  end

  def new
    @tracks = Track.all
    @note = Note.new #necessary for refilling forms?
    render :new
  end

  def create
    @tracks = Track.all
    @note = Note.new(params[:note])
    if @note.save
      redirect_to Track.find(@note.track_id)
    else
      render :new
    end

  end

  def edit
    @note = Note.find(params[:note][:id])

    render :edit
  end

  def update
    @note = Note.find(params[:note][:id])
    @note.update_attributes(params[:note])
    if @note.save
      redirect_to @note
    else
      render :edit
    end
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy

    redirect_to track_url # refer back.
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # this is where you log in.
    render :new
  end

  def create
    user = User.find_by_email(params[:user][:email])

    if user.verify_password(params[:user][:password])
      user.reset_session_token!
      session[:session_token] = user.session_token

      redirect_to bands_url
    else
      flash[:notices] ||= []
      flash[:notices] << "Username/password combo sucks."

      redirect_to new_session_url
      # redirect_to bands_url # incorrect. checnge
      #redirect to login page
    end
  end

  def destroy
    user = current_user

    if user.nil?
      redirect to new_session_url
      return
    end

    session[:session_token] = nil
    user.session_token = nil
    user.save!

    redirect to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find(params[:id])
    @album = Album.find(@track.album_id)
    render :show
  end

  def new
    @albums = Album.all
    @track = Track.new #necessary for refilling forms?
    render :new
  end

  def create
    @albums = Album.all
    @track = Track.new(params[:track])
    if @track.save
      redirect_to Album.find(@track.album_id)
    else
      render :new
    end

  end

  def edit
    @track = Track.find(params[:track][:id])

    render :edit
  end

  def update
    @track = Track.find(params[:track][:id])
    @track.update_attributes(params[:track])
    if @track.save
      redirect_to @track
    else
      render :edit
    end
  end

  def destroy
    album = Track.find(params[:id])
    album.destroy

    redirect_to albums_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    @user = User.new #necessary for refilling forms?
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      msg = UserMailer.welcome_email(@user)
      msg.deliver!
      redirect_to bands_url
    else
      render :new
    end

  end

  def edit
    @user = User.find(params[:user][:id])

    render :edit
  end

  def update
    @user = User.find(params[:user][:id])
    @user.update_attributes(params[:user])
    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    redirect_to users_url
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
#encoding: utf-8
module TracksHelper

  def gay_lyrics(text_block)
    html = "</p>"
    lyric_lines = text_block.split("\n")
    lyric_lines.each do |line|
      html += "♫    "
      html += line
      html += '<br>'
    end

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<!-- <% options_for_select(@bands.map {|band| [band.name,band.id]})   %> -->



<!-- add default values -->

<label for="band">Band</label>
<select name="album[band_id]" id="band">
	<% @bands.each do |band|%>
		<option value= "<%= band.id %>" > <%= band.name %> </option>
	<% end %>
</select>
<br>

<label for="album_name">Album name</label>
	<input name="album[name]" id="album_name" type="text" value = "<% @album.name %>" >
<br>

<label for="album_recording">Album Recording</label>
	<select name="album[recording]" id="album_recording">
		<option value='live'>Live</option>
		<option value='studio'>Studio</option>
	</select>
<br>

<input type ="submit" value="Submit">

app/views/albums/edit.html.erb
<h1> Edit Band details</h1>

<%= @album.errors.messages %>
<form action="/albums/<% @album.id %>" method= "put">

	<%= render :partial => "form" %>

</form>

app/views/albums/index.html.erb
<h1>Albums</h1>

<ul>

	<% @albums.each do |album|%>
		<li> <%= album.name %>
		</li>
	<% end %>

</ul>

app/views/albums/new.html.erb
<h1> Add an Album </h1>

<%= @album.errors.messages %>

<form action="/albums" method= "post">

	<%= render :partial => "form" %>

</form>
<p><%= link_to "Back to Bands index", "/bands/" %></p>

app/views/albums/show.html.erb
<h1> <%= @album.name %> </h1>

<h3> Tracks </h3>

<ul>
	<% @album.tracks.each do |track| %>
	<li> <%= link_to "#{track.title}", track %> </li>

	<% end %>
</ul>

<p>
<%= link_to "Add new track", new_track_url %>
</p>


<%= button_to "Destroy Album" , {:controller => :albums, :confirm => "Are you sure?", :action => "destroy" }, :method => "delete" %>

<p>
<%= link_to "Back to #{@band.name}", @band %>
</p>

app/views/bands/_form.html.erb
<label for="band_name">Band name</label>
<input name="band[name]" id="band_name" type="text" value = "<% @band.name %>" >
<br>

<input type ="submit" value="Start Making Music">

app/views/bands/edit.html.erb
<h1> Edit Band details</h1>

<%= @band.errors.messages %>
<form action="/bands/<% @band.id %>" method= "put">

	<%= render :partial => "form" %>

</form>

app/views/bands/index.html.erb
<h1>Bands in record</h1>

<ul>

	<% @bands.each do |band|%>
		<li> 	<%= link_to "#{band.name}", band %>
		</li>
	<% end %>

</ul>

<%= link_to "Add a band!", new_band_url %>

app/views/bands/new.html.erb
<h1> Create/Register a Band </h1>

<%= @band.errors.messages %>

<form action="/bands" method= "post">

	<%= render :partial => "form" %>

</form>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>


<h3>Albums</h3>

<ul>
<% @band.albums.each do |album| %>
	<li><%= link_to album.name, album %></li>
<% end %>
</ul>

<p>
	<%= link_to "Add new album", new_album_url%>
</p>

<%= button_to "Delete Band", {:controller => :bands, :confirm => "Are you sure?", :action => "destroy" }, :method => "delete" %>


<p>
<%= link_to "Back to bands index", bands_url %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<!-- <#% options_for_select(@tracks.map {|track| [track.name,track.id]})   %> -->



<!-- add default values -->

<label for="track">Track</label>
<select name="note[track_id]" id="track">
	<% @tracks.each do |track|%>
		<option value= "<%= track.id %>" > <%= track.title %> </option>
	<% end %>
</select>
<br>

<label for="note_content">Note</label>
	<textarea name="note[content]" id="note_content"></textarea>
<br>


<input type ="submit" value="Submit">

app/views/notes/_note.html.erb
<h4>Add Note:</h4>

<textarea name="note[content]" id="note_content"></textarea>
<input name="note[track_id]" type="hidden" value= '<%= @track.id %>' >
<br>

<%= button_to "Submit note",
		{:controller => :notes, :action => "create"},
		:method => "post" %>

app/views/notes/edit.html.erb
<h1> Edit Band details</h1>

<%= @track.errors.messages %>
<form action="/tracks/<% @track.id %>" method= "put">

	<%= render :partial => "form" %>

</form>

app/views/notes/index.html.erb
<h1>Tracks</h1>

<ul>

	<% @tracks.each do |track|%>
		<li> <%= track.title %>
		</li>
	<% end %>

</ul>

app/views/notes/new.html.erb
<h1> Add a note</h1>

<%= @note.errors.messages %>

<form action="/notes" method= "post">

	<%= render :partial => "form" %>

</form>

app/views/tracks/_form.html.erb
<!-- <% options_for_select(@albums.map {|album| [album.name,album.id]})   %> -->



<!-- add default values -->

<label for="album">Album</label>
<select name="track[album_id]" id="album">
	<% @albums.each do |album|%>
		<option value= "<%= album.id %>" > <%= album.name %> </option>
	<% end %>
</select>
<br>

<label for="track_title">Track title</label>
	<input name="track[title]" id="track_title" type="text" value = "<% @track.title %>" >
	<select name="track[track_type]" id="track_title">
		<option value='regular'>Regular</option>
		<option value='bonus'>Bonus</option>
	</select>
<br>

<label for="track_lyrics">Lyrics</label>
	<textarea name="track[lyrics]" id="track_lyrics"></textarea>
<br>


<input type ="submit" value="Submit">

app/views/tracks/edit.html.erb
<h1> Edit Band details</h1>

<%= @track.errors.messages %>
<form action="/tracks/<% @track.id %>" method= "put">

	<%= render :partial => "form" %>

</form>

app/views/tracks/index.html.erb
<h1>Tracks</h1>

<ul>

	<% @tracks.each do |track|%>
		<li> <%= track.title %>
		</li>
	<% end %>

</ul>

app/views/tracks/new.html.erb
<h1> Add a track</h1>

<%= @track.errors.messages %>

<form action="/tracks" method= "post">

	<%= render :partial => "form" %>

</form>

app/views/tracks/show.html.erb
<h1> <%= @track.title %> </h1>

<h3> Lyrics </h3>
	<%= gay_lyrics(@track.lyrics)%>
<br>

<h3>Notes on this track</h3>

<ol>
	<% @track.notes.each do |note|%>
	<li> <%= note.content %> </li>


	<% end %>
</ol>

<form action="/notes" method= "post">
	<%= render :partial => "/notes/note" %>
</form>

<br>

<%= button_to "Destroy Track", {:controller => :tracks, :confirm => "Are you sure?", :action => "destroy" }, :method => "delete" %>

<p><%= link_to "Back to #{@album.name}", @album %></p>

app/views/users/_form.html.erb
<!-- <%# options_for_select(@bands.map {|band| [band.name,band.id]})   %> -->



<!-- add default values -->
<h2> Register </h2>

<label for="user_email">Email</label>
	<input name="user[email]" id="user_email" type="text" value = "<% @user.email %>" >
<br>

<label for="user_password">Create a Password</label>
	<input name="user[password]" id="user_password" type="password" >
<br>

<input type ="submit" value="Submit">

app/views/users/edit.html.erb
<h1> Edit Band details</h1>

<%= @album.errors.messages %>
<form action="/albums/<% @album.id %>" method= "put">

	<%= render :partial => "form" %>

</form>9

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
	<% @users.each do |user| %>
	<li><%= user.email %> </li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1> Sign up for this AWESOME record base. </h1>

<%= @user.errors.messages %>

<form action="/users" method= "post">

	<%= render :partial => "form" %>

</form>

app/views/users/show.html.erb
<h1> <%= @album.name %> </h1>

<h3> Tracks </h3>

<ul>
	<% @album.tracks.each do |track| %>
	<li> <%= link_to "#{track.title}", track %> </li>

	<% end %>
</ul>

<p>
<%= link_to "Add new track", new_track_url %>
</p>


<%= button_to "Destroy Album" , {:controller => :albums, :confirm => "Are you sure?", :action => "destroy" }, :method => "delete" %>

<p>
<%= link_to "Back to #{@band.name}", @band %>
</p>